version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  my-cache:
    build: .
    restart: on-failure
    depends_on:
      - db
    ports:
      - "80:80"
    environment:
      - STORAGE=pg
      - PG_HOST=db
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PWD=postgres
      - PG_DB=cache_app